Php sdk integration
mobbexco/prestashop pull request #146
Opened 2022-12-16 19:43 UTC by EMunozMobbex

2023-04-28 14:05 UTC, jlmobbex commented on mobbex/Models/Helper.php
> -<?php
Esto quedó desactualizado, creo que señalé algunas más en los comentarios

2023-04-28 15:09 UTC, EMunozMobbex commented on mobbex/Models/Transaction.php
> +            'source_url'         => isset($res['payment']['source']['url']) ? json_encode($res['payment']['source']['url']) : '',
'Source Expiration' y 'Source Installment' son arrays, esos 2 requieren ser encodeados, 'source url' no

2023-05-05 13:49 UTC, jlmobbex requested changes

2023-05-05 13:49 UTC, jlmobbex commented on mobbex/controllers/front/notification.php
> +        $trx = \Mobbex\PS\Checkout\Models\Transaction::getTransactions($cartId, true);
No hace falta volver a traer la trx de la base de datos. En master se ve que ahora el método saveTransaction devuelve la instancia de la `transaction`. Así que quedaría en una sóla línea y se ahorraría la consulta a db

2023-05-05 13:49 UTC, jlmobbex commented on mobbex/Models/Transaction.php
> +            'status'             => isset($res['payment']['status']['resultCode']) ? (int) $res['payment']['status']['resultCode'] : '',
Por compatibilidad con versiones anteriores status tendría que que tener también el valor del status code

2023-05-05 19:25 UTC, merged