[ECO-413] Add cart rules models
mobbexco/prestashop pull request #191
Opened 2023-06-21 13:32 UTC by mobbexLuis

2023-07-10 04:20 UTC, jlmobbex requested changes

2023-07-10 04:20 UTC, jlmobbex commented on mobbex/Models/CartRules.php
> +    public static function getRuleProduct($products, $rule, $conditions)
`$conditions` necesita una buena explicación en la doc para no perdernos (revisa que los params estén bien en la doc también).

2023-07-10 14:34 UTC, mobbexLuis commented on mobbex/Models/CartRules.php
> +                $rulesProducts = self::getSpecificRule($rule, !empty($rulesProducts) ? $rulesProducts : $products);
$rulesProducts agrupa a los productos y les añade a cada producto -segun la cart rule- una nueva posición ['rules_discount'] dentro del método correspondiente. Esta orientado de esa manera mas que nada por la cart rule que aplica a toda la orden.

si, lo del ternario lo puedo mejorar modificar situandolo despues del foreach y asiganandolo a products. De esa manera puedo pasar $products como param a los métodos y se reduce el scope.  No puede estar fuera del foreach porque se requiere verificar en cada iteración si ya se aplicaron descuentos para acumularlos en $rulesProducts.

2023-07-11 14:39 UTC, jlmobbex commented on mobbex/Models/CartRules.php
> +                $rulesProducts = self::getSpecificRule($rule, !empty($rulesProducts) ? $rulesProducts : $products);
Claro, pero si existen varias reglas, se va a asobrescribir la variable `$rulesProducts` en cada iteración. Esto es lo que veo raro, puede pasar?

En cuanto al ternario, podés simplemente sobrescribir la variable `$products` no? De esa forma te ahorrás el ternario y la definición de la variable `$rulesProducts`.

2023-07-11 21:17 UTC, mobbexLuis commented on mobbex/Models/CartRules.php
> +                $rulesProducts = self::getSpecificRule($rule, !empty($rulesProducts) ? $rulesProducts : $products);
ahi va, ya entendi a lo que te referias :)

2023-07-17 17:58 UTC, EMunozMobbex commented on mobbex/Models/OrderHelper.php
> +        $products = !$cart->getCartRules() ? $cart->getProducts(true) : (new \Mobbex\PS\Checkout\Models\PriceCalculator($cart))->applyCartRules();
Esto mas a modo de sugerencia pero me resulta un poco ilegible este código, pienso en que dentro de price calculator se obtiene la lista de products, y también el cart y si esa comprobación se hiciera dentro de PriceCalculator?

quizás podría quedar $products = $priceCalculator->getProducts;

2023-07-17 18:32 UTC, mobbexLuis commented on mobbex/Models/OrderHelper.php
> +        $products = !$cart->getCartRules() ? $cart->getProducts(true) : (new \Mobbex\PS\Checkout\Models\PriceCalculator($cart))->applyCartRules();
Esta bueno. Y que si no hay cart rules retorne products sin modificar

2023-07-26 17:07 UTC, EMunozMobbex approved these changes

2023-07-27 15:04 UTC, jlmobbex commented on mobbex/Models/OrderHelper.php
> +        $products = !$cart->getCartRules() ? $cart->getProducts(true) : (new \Mobbex\PS\Checkout\Models\PriceCalculator($cart))->applyCartRules();
Buenísimo este cambio!

2023-08-31 04:29 UTC, jlmobbex requested changes

2023-08-31 18:35 UTC, mobbexLuis commented on mobbex/Models/PriceCalculator.php
> +                $product['rules_discount'] = $this->getDiscount($product, $rule);
Acá elegí acumular los descuentos en una nueva posición para que el descuento se haga siempre a partir del precio base del producto.
Es mas que nada para casos en donde a un producto se le aplica mas de un cupon.
Ej: tenemos un cupon de carrito del 10% y ademas otro que descuenta 20% al producto mas bajo.
Presta aplica siempre el descuento sobre el valor base, entonces si ese producto vale 10, hace el descuento del 10% de 10 y luego el 20% de 10. En otro caso se estaria haciendo el 10% de 10 y luego el 20% de 9,  yeste resultado no coincidiria con el que muestra prestashop en el checkout.

2023-08-31 18:37 UTC, mobbexLuis commented on mobbex/Models/PriceCalculator.php
> +                $product['rules_discount'] = $this->getDiscount($product, $rule);
![image](https://github.com/mobbexco/prestashop/assets/118828199/7b7606de-0d2b-4b8b-beb3-47321b730212)

acá un ejemplo donde se aplica un 10% al carro y un 30% al producto de mas bajo valor.

2023-08-31 21:51 UTC, jlmobbex commented on mobbex/Models/PriceCalculator.php
> +                $product['rules_discount'] = $this->getDiscount($product, $rule);
Entendido! Lo único que me queda como recomendación es que dado que  `$conditionKey = '' && $conditionValue = ''` y `$product[$conditionKey] == $conditionValue` ejecutan el mismo código finalmente sería más legible usar un or (`||`). Por otro lado, para simplificar la condición podrías simplemente chequear si  `!$conditionKey || $product[$conditionKey] == $conditionValue`, ya que tendría el mismo resultado y es bastante más corto

2023-09-01 20:19 UTC, merged