[ECO-415] Avoid duplicated missing dni logs
mobbexco/prestashop pull request #194
Opened 2023-07-07 19:39 UTC by EMunozMobbex

2023-07-18 20:58 UTC, mobbexLuis approved these changes

2023-07-27 14:57 UTC, jlmobbex requested changes

2023-07-27 14:57 UTC, jlmobbex commented on mobbex/Models/OrderHelper.php
> +                $this->getCustomer($cart, $webhooks),
En vez de agregarle un param `$finalCheckout`, podría agregarse el log más arriba en este mismo método, como se hace en master para redireccionar a la página. Lo propongo porque creo que `getCustomer` podríamos querer usarlo en otros contextos por fuera del checkout, y tendríamos que pasar ese param siempre, aunque no hayan webhooks o un `$finalCheckout`

2023-07-28 14:41 UTC, jlmobbex approved these changes

2023-07-28 14:41 UTC, merged