[ECO-447] Integrated with php-plugins-sdk table model.
mobbexco/prestashop pull request #199
Opened 2023-07-26 17:22 UTC by EMunozMobbex

2023-07-26 19:50 UTC, mobbexLuis commented on mobbex/Models/Db.php
> +class Db extends \Mobbex\Model\AbstractDb
El namespace se cambio a \Mobbex\Model\Db

2023-07-26 20:27 UTC, mobbexLuis commented on mobbex/utils/transaction-definition.php
> +    ['Field' => 'id',                 'Type' => 'int(11)',       'Null' => 'NO', 'Key' => 'PRI', 'Extra' => 'auto_increment', 'Default' => null],
Estaria bueno que la key 'Extra' este al final para que visualmente quede mejor

2023-07-27 15:20 UTC, mobbexLuis approved these changes

2023-08-07 12:47 UTC, mobbexLuis approved these changes

2023-08-31 04:36 UTC, jlmobbex requested changes

2023-08-31 04:36 UTC, jlmobbex commented on mobbex/Models/Installer.php
> +            $definition = $tableName === 'transaction' ? include __DIR__ . "/../utils/transaction-definition.php" : [];
Mejor usar rutas absolutas de ahora en más (no poner `/../`). Para esto se podría definir una constante en el archivo principal del plugin que establezca el `__DIR__`

2023-08-31 04:36 UTC, jlmobbex commented on mobbex/utils/transaction-definition.php
> +return [
Fijate que el campo extra está quedando afuera de los array de columnas (exepto en la del `id`). Me encanta la nueva sintaxis!! 😄

2023-09-19 20:32 UTC, EMunozMobbex commented on mobbex/utils/transaction-definition.php
> +return [
Esto se modificó en el commit 64e5f95

2023-09-19 20:32 UTC, EMunozMobbex commented on mobbex/Models/Installer.php
> +            $definition = $tableName === 'transaction' ? include __DIR__ . "/../utils/transaction-definition.php" : [];
Esto se modificó en el commit 64e5f95

2023-12-12 12:54 UTC, jlmobbex approved these changes

2023-12-12 12:58 UTC, merged