[ECO-733] Added the plan description in the plans filter configuration.
mobbexco/prestashop pull request #228
Opened 2024-01-22 13:42 UTC by EMunozMobbex

2024-01-23 19:41 UTC, mobbexLuis approved these changes

2024-01-24 18:42 UTC, jlmobbex requested changes

2024-01-24 18:42 UTC, jlmobbex commented on mobbex/views/templates/hooks/plans-filter.tpl
> +                        <p>{{$field['description']}}</p>
Agreguemos un isset para asegurar que no rompa ni arroje logs:
https://stackoverflow.com/questions/5952778/if-not-isset-smarty

2024-01-29 20:01 UTC, jlmobbex approved these changes

2024-01-29 21:56 UTC, merged