Refactor in mobbex sources
mobbexco/prestashop pull request #86
Opened 2021-12-23 13:30 UTC by Emitsu55

2022-01-23 22:25 UTC, jlmobbex requested changes

2022-01-23 22:25 UTC, jlmobbex commented on mobbex/classes/MobbexHelper.php
> +        $sources = Configuration::get('MOBBEX_SOURCES_COMMON') ? json_decode(Configuration::get('MOBBEX_SOURCES_COMMON'), true) : 'se consulto la api';
En caso de no existir el valor guardado deberían obtenerse y luego guardarse consultando a la API. Además, en caso de que el valor sea falso, el if ternario debería devolver un array vacío (para que no se rompa el foreach luego)

2022-01-23 22:25 UTC, jlmobbex commented on mobbex/classes/MobbexHelper.php
> +        $sources_advanced = Configuration::get('MOBBEX_SOURCES_ADVANCED') ? json_decode(Configuration::get('MOBBEX_SOURCES_ADVANCED'), true) : 'se hizo masl';
Acá aplicaría lo mismo que en el comentario anterior

2022-01-23 22:25 UTC, jlmobbex commented on mobbex/mobbex.php
> +        $price   = $total ?: number_format($product->getPrice(), 2);
Este cambio sobrescribe un fix que está en master sobre el precio

2022-01-24 13:01 UTC, Emitsu55 commented on mobbex/classes/MobbexHelper.php
> +        $sources = Configuration::get('MOBBEX_SOURCES_COMMON') ? json_decode(Configuration::get('MOBBEX_SOURCES_COMMON'), true) : 'se consulto la api';
Se me paso ahi colocar las consultas a la api! Ya lo corregí ahora lo pulleo gracias javi!

2022-01-24 13:27 UTC, jlmobbex requested changes

2022-01-24 13:27 UTC, jlmobbex commented on mobbex/controllers/front/sources.php
> +        if(Tools::getValue('hash') !== md5(MobbexHelper::K_API_KEY . '!' . MobbexHelper::K_ACCESS_TOKEN))
Otro cosita que vi hoy, el hash se está creando con los strings que funcionan como key para obtener las credenciales en lugar de las credenciales en si. Habría que pasar a usar esas credenciales para que el hash no sea el mismo siempre.

2022-02-15 13:07 UTC, jlmobbex requested changes

2022-02-15 13:07 UTC, jlmobbex commented on mobbex/classes/MobbexHelper.php
> +        $sources = Configuration::get('MOBBEX_SOURCES_COMMON') ? json_decode(Configuration::get('MOBBEX_SOURCES_COMMON'), true) : self::getSources();
Cuando se obtienen los planes directamente de getSources también deberían guardarse en la config, porque sino cuando esta se encuentre vacía (por la razón que sea) se llamaría a la API cada vez que se muestran.

2022-02-23 23:17 UTC, jlmobbex requested changes

2022-02-23 23:17 UTC, jlmobbex commented on mobbex/mobbex.php
> +        $hash = md5(MobbexHelper::K_API_KEY . '!' . MobbexHelper::K_ACCESS_TOKEN);
Recién me di cuenta, acá faltan obtener las configs (API key y Access token) para generar el hash

2022-02-24 12:50 UTC, Emitsu55 commented on mobbex/mobbex.php
> +        $hash = md5(MobbexHelper::K_API_KEY . '!' . MobbexHelper::K_ACCESS_TOKEN);
que raro recordaba que ya lo habia resuelto esto, ahora lo arreglo!

2022-02-24 20:27 UTC, jlmobbex requested changes

2022-02-24 20:27 UTC, jlmobbex commented on mobbex/mobbex.php
> +        $hash = md5(\Configuration::get(MobbexHelper::K_API_KEY) . '!' . \Configuration::get(MobbexHelper::K_API_KEY));
El hash en esta línea está tomando en los dos casos la config K_API_KEY

2022-02-25 21:19 UTC, merged